server:
  port: 8087

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/restapiapp?serverTimezone=UTC
    username: root
    password: qaz923923
  flyway:
    url: jdbc:mysql://localhost:3306/restapiapp?serverTimezone=UTC
    user: root
    password: qaz923923
    locations: db/migration
jwt:
  secret: stjgJYvZsQjkH69IX2prakSSIgd0Iygi
  expiration: 4000

aws:
  credentials:
    accessKey: AKIAVRUVRQESJVDVQUWG
    secretKey: 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
  bucket:
    name: com.vladkostromin.s3app.bucket
    region: eu-central-1
  localFolder: src/main/resources/download/
