server:
  port: 8087

spring:
  r2dbc:
    url: r2dbc:mysql://db:3306/restapiapp?serverTimezone=UTC
    username: root
    password: qaz923923
  flyway:
    url: jdbc:mysql://db:3306/restapiapp?serverTimezone=UTC
    user: root
    password: qaz923923
    locations: db/migration
jwt:
  secret: stjgJYvZsQjkH69IX2prakSSIgd0Iygi
  expiration: 4000

aws:
  credentials:
    accessKey: *****
    secretKey: *****
  bucket:
    name: bucket
    region: region
  localFolder: src/main/resources/download/
