server:
  port: 8087

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/restapiapp?serverTimezone=UTC
    username: user
    password: password
  flyway:
    url: jdbc:mysql://localhost:3306/restapiapp?serverTimezone=UTC
    user: user
    password: password
    locations: db/migration
jwt:
  secret: stjgJYvZsQjkH69IX2prakSSIgd0Iygi
  expiration: 4000

aws:
  credentials:
    accessKey: accessKey
    secretKey: secretKey
  bucket:
    name: some.bucket
    region: region
  localFolder: some/folder
